
# Configuration

# echo "ServerName localhost" | sudo tee /etc/apache2/conf-available/servername.conf
- name: apache24 | set servername.conf 
  template: >
    src={{ apache_config|default('httpd.conf.j2') }}
    dest=/etc/apache2/conf-available/servername.conf
  notify:
    - apache-restart

- name: apache24 | enable servername.conf 
  command: a2enconf servername
  notify:
    - apache-restart

- name: apache24 | set ports.conf
  template: >
    src={{ apache_ports|default('2.4/ports.conf.j2') }}
    dest={{ path_apache_ports }}
  notify:
    - apache-restart

# Virtual Hosts

- name: apache24 | add apache configurations
  template: >
    src={{ item.template|default('2.4/default.conf.j2') }}
    dest=/etc/apache2/sites-available/{{ item.name }}.conf
    mode=0640
  with_items: apache_vhosts
  when: apache_vhosts is defined
  notify:
    - apache-restart

- name: apache24 | activates our virtualhost
  command: a2ensite {{ item.name }}.conf
  with_items: apache_vhosts
  when: apache_vhosts is defined
  notify:
    - apache-restart
