# Package

- name: install | install debian apache
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_apache
  when: ansible_os_family == 'Debian'

- name: install | install rpm apache
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_apache
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']
