# Package

- name: install | install debian apache
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_apache
  when: ansible_os_family == 'Debian'

- name: install | install rpm apache
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_apache
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Configuration

- name: install | apache2 lock
  file: >
    path=/var/lock/apache2
    owner={{ apache_user }}
    group={{ apache_group }}
    mode=0755

- name: install | set envvars
  template: >
    src={{ apache_envvars|default('envvars.j2') }}
    dest=/etc/apache2/envvars
    owner=root
    group=root
    mode=0644
  notify:
    - apache-restart
  when: ansible_os_family == 'Debian'

- name: install | install apache modules
  command: a2enmod {{ item }}
  with_items: apache_modules
  when: apache_modules is defined
  notify:
    - apache-restart

- name: install | check ssl if module is enabled
  command: sudo apache2ctl -M
  register: apache_result
  ignore_errors: True

- name: install | verify ssl directory
  file: >
    path=/etc/apache2/ssl
    state=directory
  when: "'ssl_module' in apache_result.stdout"

- name: install | create self-signed SSL cert
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ ansible_fqdn }}" -keyout /etc/apache2/ssl/server.key -extensions v3_ca -out /etc/apache2/ssl/server.crt
  when: "'ssl_module' in apache_result.stdout"
  notify:
    - apache-restart
