- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: install.yml

# Figure out apache version

- name: main | get installed version of apache
  command: "{{ service_apache }} -v"
  changed_when: false
  always_run: yes
  register: _apache_version

- name: main | create apache_version variable
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- include: apache.yml

- include: apache22.yml
  when: "apache_version.split('.')[1] == '2'"

- include: apache24.yml
  when: "apache_version.split('.')[1] == '4'"

#- include: protobox.yml
#  when: protobox_env is defined and protobox_env == 'vagrant'
