- name: apache-restart
  service: >
    name={{ service_apache }}
    state=restarted

- name: apache-start
  service: >
    name={{ service_apache }} 
    state=started

- name: apache-stop
  service: >
    name={{ service_apache }} 
    state=stopped
